doc/helper/api.md, doc/helper/map.md, doc/helper/place_autocomplete.md, doc/service/service.md, src/Helper/Builder/ApiHelperBuilder.php, src/Helper/Renderer/LoaderRenderer.php, src/Service/AbstractService.php, tests/Helper/Builder/ApiHelperBuilderTest.php, tests/Helper/Renderer/LoaderRendererTest.php, tests/Service/Directions/DirectionsTest.php, tests/Service/DistanceMatrix/DistanceMatrixTest.php, tests/Service/Geocoder/GeocoderProviderTest.php, tests/Service/ServiceTest.php
This PR adds API key support for the map, place autocomplete, directions, distance matrix and geocoder services.
=> Add API key support

doc/service/geocoder/geocoder_response.md, src/Service/Geocoder/GeocoderProvider.php, src/Service/Geocoder/GeocoderResult.php, tests/Service/Geocoder/GeocoderResultTest.php
This PR adds the place id parameter to the geocoder result.
=> [Geocoder] Add place id

doc/service/directions/directions_response.md, src/Service/Directions/Directions.php, src/Service/Directions/DirectionsFare.php, src/Service/Directions/DirectionsRoute.php, tests/Service/Directions/DirectionsFareTest.php, tests/Service/Directions/DirectionsRouteTest.php
This PR adds fare support to the directions service.
=> [Directions] Add fare support

src/Service/Directions/Directions.php, src/Service/Directions/DirectionsGeocoded.php, src/Service/Directions/DirectionsGeocodedStatus.php, src/Service/Directions/DirectionsGeocodedType.php, src/Service/Directions/DirectionsResponse.php, tests/Service/Directions/DirectionsGeocodedTest.php, tests/Service/Directions/DirectionsResponseTest.php
This PR adds the missing geocoded waypoints property to the directions response.
=> [Directions] Add geocoded waypoints support

doc/service/directions/directions_request.md, src/Service/Directions/DirectionsRequest.php, src/Service/Directions/DirectionsTrafficModel.php, src/Service/Directions/DirectionsTransitMode.php, src/Service/Directions/DirectionsTransitRoutingPreference.php, tests/Service/Directions/DirectionsRequestTest.php
This PR adds missing properties on the directions request which are only available for request using an api key or a business account.
=> [Directions] Add missing request properties

doc/service/directions/directions_response.md, src/Service/Directions/Directions.php, src/Service/Directions/DirectionsLeg.php, src/Service/DistanceMatrix/DistanceMatrix.php, src/Service/Geocoder/GeocoderProvider.php, tests/Service/Directions/DirectionsLegTest.php, tests/Service/Directions/DirectionsResponseTest.php
This PR adds the duration in traffic property to the directions leg.
=> [Directions] Add duration in traffic support

doc/service/directions/directions_response.md, src/Service/Directions/Directions.php, src/Service/Directions/DirectionsLeg.php, tests/Service/Directions/DirectionsLegTest.php
This PR adds the departure/arrival time properties to the directions leg.
=> [Directions] Add departure/arrival time response support

src/Service/Base/Fare.php, src/Service/Directions/Directions.php, src/Service/Directions/DirectionsRoute.php, src/Service/DistanceMatrix/DistanceMatrix.php, src/Service/DistanceMatrix/DistanceMatrixElement.php, tests/Service/Base/FareTest.php, tests/Service/Directions/DirectionsRouteTest.php, tests/Service/DistanceMatrix/DistanceMatrixElementTest.php
This PR adds missing properties on the distance matrix element.
=> [DistanceMatrix] Add missing properties to element

README.md, doc/layer/geo_json_layer.md, doc/layer/index.md, doc/usage.md, src/Helper/Builder/MapHelperBuilder.php, src/Helper/Collector/Layer/GeoJsonLayerCollector.php, src/Helper/Event/MapEvents.php, src/Helper/Renderer/Layer/GeoJsonLayerRenderer.php, src/Helper/Renderer/MapContainerRenderer.php, src/Helper/Subscriber/Layer/GeoJsonLayerSubscriber.php, src/Helper/Subscriber/Layer/LayerSubscriber.php, src/Layer/GeoJsonLayer.php, src/Layer/LayerManager.php, tests/Helper/Collector/Layer/GeoJsonLayerCollectorTest.php, tests/Helper/Functional/AbstractMapFunctionalTest.php, tests/Helper/Functional/Layer/GeoJsonLayerFunctionalTest.php, tests/Helper/Renderer/Layer/GeoJsonLayerRendererTest.php, tests/Helper/Renderer/MapContainerRendererTest.php, tests/Layer/GeoJsonLayerTest.php, tests/Layer/LayerManagerTest.php
This PR adds geo json supports to the map.
=> [Map] Add GeoJson support

.travis.yml, UPGRADE-2.0.md, composer.json
This PR refines the composer lowest deps.
=> [Composer] Refine lowest deps

doc/map.md, src/Helper/Renderer/MapHtmlRenderer.php, src/Map.php, tests/Helper/Renderer/MapHtmlRendererTest.php, tests/MapTest.php
This PR adds html container attributes support to the map. It will allow to align features in the bundle.
=> [Map] Add html container attributes support

doc/map.md, src/Helper/Builder/MapHelperBuilder.php, src/Helper/Renderer/Overlay/Extendable/AbstractCoordinateExtendableRenderer.php, src/Helper/Renderer/Overlay/Extendable/AbstractUnionExtendableRenderer.php, src/Helper/Renderer/Overlay/Extendable/BoundsExtendableRenderer.php, src/Helper/Renderer/Overlay/Extendable/DefaultViewportExtendableRenderer.php, src/Helper/Renderer/Overlay/Extendable/HeatmapLayerExtendableRenderer.php, src/Layer/HeatmapLayer.php, src/Layer/KmlLayer.php, src/Layer/LayerManager.php, src/Map.php, tests/Helper/Functional/Layer/GeoJsonLayerFunctionalTest.php, tests/Helper/Renderer/Overlay/Extendable/BoundsExtendableRendererTest.php, tests/Helper/Renderer/Overlay/Extendable/DefaultViewportExtendableRendererTest.php, tests/Helper/Renderer/Overlay/Extendable/HeatmapLayerExtendableRendererTest.php, tests/Layer/HeatmapLayerTest.php, tests/Layer/KmlLayerTest.php, tests/Layer/LayerManagerTest.php, tests/MapTest.php
This PR adds the autozoom support for layers.
=> [Map] Add layer auto-zoom support

README.md, doc/control/custom.md, doc/control/index.md, doc/usage.md, src/Control/ControlManager.php, src/Control/CustomControl.php, src/Helper/Builder/MapHelperBuilder.php, src/Helper/Collector/Control/CustomControlCollector.php, src/Helper/Event/MapEvents.php, src/Helper/Renderer/Control/CustomControlRenderer.php, src/Helper/Subscriber/Control/ControlSubscriber.php, src/Helper/Subscriber/Control/CustomControlSubscriber.php, src/Helper/Subscriber/MapJavascriptSubscriber.php, tests/Control/ControlManagerTest.php, tests/Control/CustomControlTest.php, tests/Helper/Collector/Control/CustomControlCollectorTest.php, tests/Helper/Functional/Control/CustomControlFunctionalTest.php, tests/Helper/Renderer/Control/CustomControlRendererTest.php
=> [Map] Add custom control support

README.md, doc/control/fullscreen.md, doc/control/index.md, doc/usage.md, src/Control/ControlManager.php, src/Control/FullscreenControl.php, src/Helper/Builder/MapHelperBuilder.php, src/Helper/Renderer/Control/FullscreenControlRenderer.php, tests/Control/ControlManagerTest.php, tests/Control/FullscreenControlTest.php, tests/Helper/Functional/Control/FullscreenControlFunctionalTest.php, tests/Helper/Renderer/Control/FullscreenControlRendererTest.php
This PR adds the fullscreen control support.
=> [Map] Add fullscreen control support

src/Service/Base/Distance.php, src/Service/Base/Duration.php, src/Service/Base/Fare.php, src/Service/Direction/Direction.php, src/Service/DistanceMatrix/DistanceMatrix.php, src/Service/Elevation/Elevation.php, src/Service/Geocoder/GeocoderProvider.php, tests/Service/Base/DistanceTest.php, tests/Service/Base/DurationTest.php, tests/Service/Base/FareTest.php
=> [Service] Add some adjustments

doc/service/base.md, doc/service/direction/direction_response.md, doc/service/direction/direction_transit_details.md, src/Service/Base/Time.php, src/Service/Direction/Direction.php, src/Service/Direction/Response/DirectionLeg.php, src/Service/Direction/Response/Transit/DirectionTransitDetails.php, tests/Service/Base/TimeTest.php, tests/Service/Direction/Response/DirectionLegTest.php, tests/Service/Direction/Response/Transit/DirectionTransitDetailsTest.php
This PR introduces the `Time` class. Relying only on a `DateTime` does not allow to retrieve the original timezone in all cases...
=> [Service] Introduce time

doc/service/direction/direction.md, doc/service/distance_matrix/distance_matrix.md, doc/service/elevation/elevation.md, doc/service/geocoder/geocoder.md, doc/service/timezone/timezone.md, src/Service/Direction/DirectionService.php, src/Service/DistanceMatrix/DistanceMatrixService.php, src/Service/Elevation/ElevationService.php, src/Service/Geocoder/GeocoderService.php, src/Service/TimeZone/TimeZoneService.php, tests/Service/Direction/DirectionServiceApiKeyTest.php, tests/Service/Direction/DirectionServiceTest.php, tests/Service/DistanceMatrix/DistanceMatrixServiceApiKeyTest.php, tests/Service/DistanceMatrix/DistanceMatrixServiceTest.php, tests/Service/Elevation/ElevationServiceTest.php, tests/Service/Geocoder/GeocoderServiceApiKeyTest.php, tests/Service/Geocoder/GeocoderServiceTest.php, tests/Service/TimeZone/TimeZoneServiceTest.php
=> [Service] Add suffix to all services

src/Service/AbstractService.php, src/Service/Direction/DirectionService.php, src/Service/DistanceMatrix/DistanceMatrixService.php, src/Service/Elevation/ElevationService.php, src/Service/Geocoder/GeocoderService.php, src/Service/TimeZone/TimeZoneService.php, src/Service/Utility/JsonParser.php, src/Service/Utility/Parser.php, src/Service/Utility/ParserInterface.php, src/Service/Utility/XmlParser.php, tests/Service/ServiceTest.php, tests/Service/Utility/JsonParserTest.php, tests/Service/Utility/ParserTest.php, tests/Service/Utility/XmlParserTest.php
All is in the title. This allow to remove duplication across services.
=> [Service] Refactor parser

src/Helper/Formatter/Formatter.php, tests/Helper/Formatter/FormatterTest.php
=> [Formatter] Fix escaping

src/Helper/Collector/Overlay/InfoWindowCollector.php, src/Helper/Subscriber/Overlay/DefaultInfoWindowSubscriber.php, src/Helper/Subscriber/Overlay/InfoBoxSubscriber.php, tests/Helper/Collector/Overlay/DefaultInfoWindowCollectorTest.php, tests/Helper/Collector/Overlay/InfoBoxCollectorTest.php, tests/Helper/Collector/Overlay/InfoWindowCollectorTest.php, tests/Helper/Functional/Overlay/AbstractMarkerInfoWindowFunctionalTest.php, tests/Helper/Functional/Overlay/MarkerInfoBoxFunctionalTest.php
This PR fixes #182 and probably some other nasty bugs about info windows/boxes...
=> [Collector] Fix info window collector strategy

doc/map.md, doc/overlay/marker.md
I was trying to use this code, but it wasn't working properly, I've fix it.
=> Some errors in code example

src/Helper/Renderer/Geometry/EncodingRenderer.php, tests/Helper/Renderer/Geometry/EncodingRendererTest.php
This PR fixes https://github.com/egeloen/IvoryGoogleMapBundle/issues/183 and fixes https://github.com/egeloen/IvoryGoogleMapBundle/issues/186
=> Fix encoded polyline rendering

doc/place/autocomplete.md
=> Spelling of event

src/Helper/Renderer/Overlay/MarkerClustererRenderer.php, tests/Helper/Renderer/Overlay/MarkerClustererRendererTest.php
This PR fixes egeloen/IvoryGoogleMapBundle#193
/cc @davidromani
=> [MarkerClusterer] Fix default image path

doc/overlay/info_window.md
Slight tweak to avoid confusion with docs.
=> Documentation improvement

.env.dist, .gitattributes, .travis.yml, doc/docker.md, docker-compose.yml, docker/config/xdebug.ini, docker/hhvm/Dockerfile, docker/hhvm/config/xdebug.ini, docker/hhvm/entrypoint.sh, docker/php/Dockerfile, docker/php/config/xdebug.ini, docker/php/entrypoint.sh, travis/install.sh, travis/script.sh, travis/success.sh
This PR adds an HHVM container as well as a travis docker build.
=> [Docker] Add HHVM container

doc/map.md
change name of function to one that exists.
=> Update setHtmlId to setHtmlContainerId

doc/map.md, src/Helper/Builder/StaticMapHelperBuilder.php, src/Helper/Event/StaticMapEvents.php, src/Helper/Renderer/Image/StyleRenderer.php, src/Helper/Subscriber/Image/StaticSubscriber.php, src/Helper/Subscriber/Image/StyleSubscriber.php, tests/Helper/Functional/StaticMapFunctionalTest.php, tests/Helper/Renderer/Image/StyleRendererTest.php
=> [Helper] Add static map styles support
